# Local development specific settings
spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose-local.yml
spring.docker.compose.lifecycle-management=START_ONLY

# Local database
spring.datasource.url=jdbc:postgresql://localhost:5432/u_announce
spring.datasource.username=postgres
spring.datasource.password=postgres

# Local environment URLs
environment.host=localhost:${server.port}
environment.protocol=http
environment.frontend.path=http://localhost:5173
environment.api.path=http://localhost:8080