# Local development specific settings
spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose-local.yml
spring.docker.compose.lifecycle-management=START_ONLY

# Local database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# Local environment URLs
environment.host=localhost:${server.port}
environment.protocol=http
environment.frontend.path=http://localhost:5173
environment.api.path=http://localhost:8080

# SpringDoc OpenAPI/Swagger configuration
springdoc.swagger-ui.oauth.client-id=u-announce-frontend

# Keycloak admin client configuration
keycloak.admin.server-url=http://localhost:9000
keycloak.admin.realm=u-announce
keycloak.admin.client-id=u-announce-backend
keycloak.admin.client-secret=u-announce-backend-secret

# uAnnounce
u-announce.security.master-key=TbeMl9AI/+2bMBcoNsykbuSZOBE3dN2yDNemvvQXDSc=